### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by mruffalo** [baliga-lab/cmonkey2#50]
I exclusively use Python 3, and found it to be kind of a pain to have to set up a completely separate Python environment to use cmonkey2.

Are there any plans to make cmonkey2 work under current Python (e.g. 3.4+)? I'm quite willing to submit patches and pull requests to update the code to run under 2.x and 3.x from the same source code, and adding the `six` package as a dependency would make this significantly easier.

**Comment by weiju** [comment]
Hi, I've made changes to run cmonkey2 both under Python2 and Python3. The unit tests run through for both Python versions and I am currently running complete runs to make sure I didn't miss anything. After that I will commit an updated version. BTW, are you using cmviewer ? I haven't made changes to that yet, but this will follow, too

**Comment by weiju** [comment]
I have tested the changes for compatibility for both Python 2 and Python 3, merged and pushed onto master

**Comment by mruffalo** [comment]
Much appreciated! I'll be happy to delete that otherwise-useless Python 2.7 virtualenv.
