### ISSUE TITLE
executable paths

### ISSUE THREAD

**Issue by adelomana** [baliga-lab/cmonkey2#55]
On my machine some executable are in a different path, it might be a good idea to add /usr/bin as a possible path for uname and awk

Gates 2016-08-15 10:48:00 ~/gDrive2/projects/TREES-C/PfuEGRIN/src/cmonkeyRuns : ./command.sh 
2016-08-15 10:49:30 INFO     checking MEME...
/bin/uname: Command not found.
/bin/awk: Command not found.
2016-08-15 10:49:30 INFO     Input matrix has # rows: 3, # columns: 3
2016-08-15 10:49:30 INFO     # clusters/row: 2

Gates 2016-08-15 10:54:45 ~/projects/green/data/input4cmonkey : ls /usr/bin/awk 
/usr/bin/awk
Gates 2016-08-15 14:10:14 ~/projects/green/data/input4cmonkey : ls /usr/bin/uname
/usr/bin/uname
Gates 2016-08-15 14:10:19 ~/projects/green/data/input4cmonkey :

**Comment by weiju** [comment]
these error messages come from the meme script, cmonkey2 itself does not have as many shell tool dependencies.

**Comment by adelomana** [comment]
thanks Wei-Ju!
