### ISSUE TITLE
Python 2.7.x/pip Installation issue (was: I can't load.)

### ISSUE THREAD

**Issue by jacobvalenzuela** [baliga-lab/cmonkey2#56]
palomino:Val_Tests jake$ pip install cmonkey2
Collecting cmonkey2
  Downloading cmonkey2-1.2.0-py2.py3-none-any.whl (1.0MB)
    100% |████████████████████████████████| 1.0MB 245kB/s 
Collecting biopython (from cmonkey2)
  Downloading biopython-1.67.tar.gz (14.3MB)
    100% |████████████████████████████████| 14.3MB 18kB/s 
Requirement already satisfied (use --upgrade to upgrade): scipy in /Users/jake/anaconda/lib/python2.7/site-packages (from cmonkey2)
Requirement already satisfied (use --upgrade to upgrade): pandas in /Users/jake/anaconda/lib/python2.7/site-packages (from cmonkey2)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /Users/jake/anaconda/lib/python2.7/site-packages (from cmonkey2)
Requirement already satisfied (use --upgrade to upgrade): numpy in /Users/jake/anaconda/lib/python2.7/site-packages (from cmonkey2)
Collecting configparser (from cmonkey2)
  Downloading configparser-3.5.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /Users/jake/anaconda/lib/python2.7/site-packages (from cmonkey2)
Collecting cherrypy (from cmonkey2)
  Downloading CherryPy-7.1.0.tar.gz (416kB)
    100% |████████████████████████████████| 417kB 556kB/s 
Requirement already satisfied (use --upgrade to upgrade): lxml in /Users/jake/anaconda/lib/python2.7/site-packages (from cmonkey2)
Collecting routes (from cmonkey2)
  Downloading Routes-2.3.1.tar.gz (181kB)
    100% |████████████████████████████████| 184kB 852kB/s 
Collecting rpy2 (from cmonkey2)
  Downloading rpy2-2.8.2.tar.gz (186kB)
    100% |████████████████████████████████| 188kB 1.3MB/s 
    Complete output from command python setup.py egg_info:
    Warning: Tried to guess R's HOME but no command (R) in the PATH.

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ch/v4y76w5s71v49lgcgtl_dwj40000gt/T/pip-build-LyPIgo/rpy2
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by weiju** [comment]
It looks like you don't have R in your path, and the problem is when you try to install rpy2, could you try to install rpy2 separately ? Looks like you are anaconda, which should not be a problem, but I haven't tried it yet, are you on a Mac, Windows or Linux ?

**Comment by jacobvalenzuela** [comment]
mac


Jacob J. Valenzuela, Ph.D.
Institute for Systems Biology
401 Terry Ave N
Seattle WA 98109
(206)-732-1496
https://www.systemsbiology.org
Jake.Valenzuela@systemsbiology.org

**Comment by jacobvalenzuela** [comment]
I got this error when installing rpy2


palomino:~ jake$ pip install rpy2

Collecting rpy2

  Using cached rpy2-2.8.2.tar.gz

    Complete output from command python setup.py egg_info:

    Warning: Tried to guess R's HOME but no command (R) in the PATH.



    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in
/private/var/folders/ch/v4y76w5s71v49lgcgtl_dwj40000gt/T/pip-build-wR0bki/rpy2/


Jacob J. Valenzuela, Ph.D.
Institute for Systems Biology
401 Terry Ave N
Seattle WA 98109
(206)-732-1496
https://www.systemsbiology.org
Jake.Valenzuela@systemsbiology.org

**Comment by weiju** [comment]
so it seems that your R is installed in a way that it is not visible from the command line, maybe you are using RStudio as a Mac OS X app, or something like that ?
For this to work, typically, you will have to install R in a way that it can be called from the command line, e.g. on the Mac that is typically done through Homebrew or Macports.

**Comment by weiju** [comment]
we have now solved this by using a centralized version on our ISB servers
