### ISSUE TITLE
Options for running cMonkey2 with an organism that is not included in the KEGG database

### ISSUE THREAD

**Issue by vvelasqz** [baliga-lab/cmonkey2#70]
I was wondering if I can run cMonkey with my own set of RSAT files without relying on the KEGG database. I have already the promoters data and motif information that I would like to include.

**Comment by weiju** [comment]
yes, this is possible, we have a wiki entry for user-provided RSAT files

https://github.com/baliga-lab/cmonkey2/wiki/Input-file-formats

If you run cmonkey2 with the --help option, you can see that the parameters --rsat_dir and --rsat_organism are dedicated to this purpose.
