### ISSUE TITLE
Minor bug in stringdb.py

### ISSUE THREAD

**Issue by izzi-13** [baliga-lab/cmonkey2#71]
Hi,
In line 99 of stringdb.py, I think 'total_nodes += 1' should be tabbed over (so it's within the 'if not node in keep_node:' block), as currently it counts each gene more than once. (This means that even if every node gets excluded, the output suggests that some have been included, which isn't helpful when trying to work out where things have gone wrong!)
Thanks!
Isabel

**Comment by izzi-13** [comment]
Have now submitted a pull request.

**Comment by weiju** [comment]
Hi, thanks for reporting the issue and sending the pull request. I have now merged your changes
